# Generated by Django (manual stub) - reintroduce missing node
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic",
            field=models.URLField(blank=True, null=True),
        ),
    ]
