# Generated by Django 5.2.7 on 2025-10-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
