# Generated by Django 5.2.7 on 2025-11-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='other_payment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='paypal_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='venmo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
