# Generated by Django 5.2.7 on 2025-11-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_other_payment_url_customuser_paypal_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='other_payment_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='paypal_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='venmo_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='other_payment_note',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='paypal_handle',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='venmo_handle',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
