# Generated by Django 5.2.7 on 2025-11-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_other_payment_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sustainability_interests',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
