# Generated by Django 5.2.7 on 2025-12-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="pending_sale",
            field=models.BooleanField(default=False),
        ),
    ]
