# Generated by Django 5.2.7 on 2025-12-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedapp', '0002_post_pending_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
